name: Test and publish

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn --frozen-lockfile
      - run: yarn lint
      - run: yarn build
      - name: Start server for oauth processing
        run: yarn serve > serve.out 2>serve.err &
        env:
          DOMAIN: ${{secrets.DOMAIN}}
          INTEGRATION_ID: ${{secrets.INTEGRATION_ID}}
          SECRET_KEY: ${{secrets.SECRET_KEY}}
          TUNNEL_SUBDOMAIN: ${{secrets.TUNNEL_SUBDOMAIN}}
          SERVER_PORT: 3000
      - name: Start tunnel
        run: yarn tunnel > /dev/null &
        env:
          TUNNEL_SUBDOMAIN: ${{secrets.TUNNEL_SUBDOMAIN}}
          SERVER_PORT: 3000
      - name: Cypress
        uses: cypress-io/github-action@v2
        env:
          DOMAIN: ${{secrets.DOMAIN}}
          INTEGRATION_ID: ${{secrets.INTEGRATION_ID}}
          TUNNEL_SUBDOMAIN: ${{secrets.TUNNEL_SUBDOMAIN}}
          USERNAME: ${{secrets.USERNAME}}
          PASSWORD: ${{secrets.PASSWORD}}
      - name: Test
        run: yarn jest
        env:
          DOMAIN: ${{secrets.DOMAIN}}
      - name: Server logs to artefacts (on error)
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: serve-logs
          path: |
            serve.out
            serve.err
      - name: Send screenshots to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          photo: cypress/creeenshots/*
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
