name: Test and publish

on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build (build needed for cypress)
        run: yarn build
      - name: Start server for oauth processing
        run: yarn serve > server.out 2>server.err &
        env:
          DOMAIN: ${{secrets.DOMAIN}}
          INTEGRATION_ID: ${{secrets.INTEGRATION_ID}}
          SECRET_KEY: ${{secrets.SECRET_KEY}}
          TUNNEL_SUBDOMAIN: ${{secrets.TUNNEL_SUBDOMAIN}}
          SERVER_PORT: 3000
          DEBUG: true
      - name: Start tunnel
        run: yarn tunnel > /dev/null &
        env:
          TUNNEL_SUBDOMAIN: ${{secrets.TUNNEL_SUBDOMAIN}}
          SERVER_PORT: 3000
#      - name: Cypress tests
#        uses: cypress-io/github-action@v5
#        env:
#          DOMAIN: ${{secrets.DOMAIN}}
#          INTEGRATION_ID: ${{secrets.INTEGRATION_ID}}
#          TUNNEL_SUBDOMAIN: ${{secrets.TUNNEL_SUBDOMAIN}}
#          USERNAME: ${{secrets.USERNAME}}
#          PASSWORD: ${{secrets.PASSWORD}}
      - name: Archive screenshots (on failure)
        if: failure()
        run: tar -czvf screenshots.tar.gz cypress/screenshots
      - name: Send screenshots to telegram (on failure)
        uses: appleboy/telegram-action@master
        if: failure()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: screenshots.tar.gz
          message: Cypress failed https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
      - name: Archive server logs (on failure)
        if: failure()
        run: tar -czvf server_logs.tar.gz server.out server.err
      - name: Send server logs to telegram (on failure)
        uses: appleboy/telegram-action@master
        if: failure()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: server_logs.tar.gz
          message: server logs https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
      - name: Publish package to npm
        uses: JS-DevTools/npm-publish@v1
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        with:
          token: ${{ secrets.NPM_TOKEN }}
